Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from Login import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Login.urls')),
    path('logout', views.user_logout, name='logout'),
]

Blog/Login/urls.py
from django.urls import path

from Login.views import PostListView
from . import views

app_name = 'Login'

urlpatterns = [
    path('', views.user_login, name='index'),
    path('home', PostListView.as_view(), name='home'),
    path('register', views.user_register, name='register'),
    path('about', views.AboutView.as_view(), name='about'),
    path('add_post', views.PostCreateView.as_view(), name='add_post'),
    path('delete/<pk>/', views.PostDeleteView.as_view(), name='delete'),
    path('update/<pk>/', views.PostUpdateView.as_view(), name='update'),
    path('add_comment/<pk>', views.add_comment, name='add_comment'),
    path('view_comment/<pk>', views.PostDetailView.as_view(), name='view_comment'),
    path('update_comment/<pk>', views.CommentUpdateView.as_view(), name='update_comment'),
    path('delete_comment/<pk>', views.CommentDeleteView.as_view(), name='delete_comment'),

]

Blog/Login/models.py
from datetime import datetime
from django.db import models
from django.urls import reverse
# Create your models here.


class Post(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    content = models.TextField()
    creation_date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse('Login:home')


class Comment(models.Model):
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    comment_text = models.CharField(max_length=400)
    commented_date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return str(self.comment_text)

    def get_absolute_url(self):
        return reverse('Login:home')

Blog/Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Comment


class UserRegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    # username = forms.CharField(max_length=30, required=True, help_text='Required.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class CommentForm(forms.ModelForm):

    class Meta():
        model = Comment
        fields = ('comment_text',)

Blog/Login/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from .forms import UserRegisterForm, CommentForm

from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, ListView, CreateView, DeleteView, UpdateView, DetailView

from .models import Post, Comment
# Create your views here.


def user_login(request):
    if request.method == 'POST':
        # print('POST REQUEST')
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('Login:home'))
            else:
                return render(request, 'Login/login.html')
        else:
            return render(request, 'Login/login.html', {"valid": True})
    else:
        return render(request, 'Login/login.html', {"valid": False})


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('Login:index'))


def user_register(request):
    registered = False
    if request.method == 'POST':
        userform = UserRegisterForm(request.POST)
        if userform.is_valid():
            # user = userform.save()
            # user.set_password(user.password)
            userform.save()
            registered = True

        else:
            print(userform.errors)

    else:
        userform = UserRegisterForm()

    context = {'user_form': userform, 'registered': registered}
    return render(request, 'Login/register.html', context)


class PostListView(LoginRequiredMixin, ListView):
    model = Post
    template_name = 'Login/home_page.html'


class AboutView(LoginRequiredMixin, TemplateView):
    template_name = 'Login/about.html'


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'Login/add_post.html'
    fields = ('author', 'title', 'content',)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'Login/update_post.html'
    fields = ('author', 'title', 'content')


class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    context_object_name = 'post_detail'
    template_name = 'Login/post_detail.html'


class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'Login/delete_post.html'
    success_url = reverse_lazy('Login:home')


@login_required
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    user = User
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.name = request.user.username
            comment.save()
            return redirect('Login:home')

    else:
        form = CommentForm()
        return render(request, 'Login/add_comment.html',{'form': form, 'title': post.title, 'user': request.user.username})


class CommentUpdateView(LoginRequiredMixin, UpdateView):
    model = Comment
    template_name = 'Login/update_comment.html'
    fields = ('comment_text',)


class CommentDeleteView(LoginRequiredMixin, DeleteView):
    model = Comment
    template_name = 'Login/delete_comment.html'
    success_url = reverse_lazy('Login:home')

Blog/templates/Login/about.html
{% extends 'Login/base.html' %}

{% block body_block %}
<h1>The Techie Blog</h1>
<p>
    The Techie blog is developed by Vignesh to post all updates regarding latest programming languages and their importance in today's world.
</p>
{% endblock %}

Blog/templates/Login/add_comment.html
{% extends 'Login/base.html' %}

{% block body_block %}
<div class="jumbotron">
<h2>{{user|lower|capfirst}} Add Comments for {{title}} </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add comment" class="btn btn-success btn-sm">
        <a href="{% url 'Login:home' %}"><button  type="button" class="btn btn-danger btn-sm">Cancel</button></a>
    </form>

</div>
{% endblock %}

Blog/templates/Login/add_post.html
{% extends 'Login/base.html' %}

{% block body_block %}
<div class="jumbotron">
<h2>Enter the details below</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add Post" class="btn btn-success btn-sm">
        <a href="{% url 'Login:home' %}"><button type="button" class="btn btn-danger btn-sm">Cancel</button></a>
    </form>

</div>
{% endblock %}

Blog/templates/Login/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@800&display=swap" rel="stylesheet">

    <style>
        li a {color:white;}
    </style>

</head>
<body style="font-family: 'Roboto Slab', serif;background-color:#AAAAAA">
<nav class="navbar fixed-top bg-dark navbar-expand-sm">

    {% if request.user.is_authenticated %}
    <a class="navbar-brand" href="{% url 'Login:home' %}" style="color:white">The Techie Blog</a>
    <div class="collapse navbar-collapse" >
        <ul class="nav navbar-nav">
            <li class="nav-item"><a class="nav-link" href="{% url 'Login:home' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'Login:about' %}">About</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'Login:add_post' %}">Add Post</a></li>
<!--            <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>-->
        </ul>
    </div>
    <div align="right">
        <a href="{% url 'logout' %}"><button type="button" class="btn btn-dark">Logout</button></a>
    </div>
    {% else %}
    <a class="navbar-brand" href="{% url 'Login:index' %}" style="color:white">The Techie Blog</a>
    <div class="collapse navbar-collapse">
    </div>
    <div align="right">
        <a href="{% url 'Login:register' %}"><button type="button" class="btn btn-dark">Sign Up</button></a>
        <a href="{% url 'Login:index' %}"><button type="button" class="btn btn-dark">Login</button></a>
    </div>
    {% endif %}

</nav>
<br>
<br>
<div class="container">
    <br>
{% block body_block %}
{% endblock %}
</div>

</body>
</html>

Blog/templates/Login/delete_comment.html
{% extends 'Login/base.html' %}
{% block body_block %}
<h3> Delete Comment: {{comment.comment_text}}</h3>


<form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
    <a href="{% url 'Login:home' %}"><button type="button" class="btn btn-warning btn-sm">Cancel</button></a>
</form>

{% endblock %}

Blog/templates/Login/delete_post.html
{% extends 'Login/base.html' %}
{% block body_block %}
<h1> Delete {{post.title}}?</h1>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-danger btn-sm">
    <a href="{% url 'Login:home' %}"><button type="button" class="btn btn-warning btn-sm">Cancel</button></a>
</form>
{% endblock %}

Blog/templates/Login/home_page.html
{% extends 'Login/base.html' %}
{% block body_block %}
<h1>Home Page</h1>


{% for post in post_list %}
<div class="jumbotron">
    <h1>{{post.title}}</h1><hr>
    <h5>Author: {{post.author}}</h5><hr>
    <p>{{post.content}}</p>
    <small>Posted on {{post.creation_date}}</small><br>
    <a href="{% url 'Login:delete' pk=post.pk %}" ><button type="button" class="btn btn-danger btn-sm">Delete Post</button></a> &nbsp;
    <a href="{% url 'Login:update' pk=post.pk %}" ><button type="button" class="btn btn-warning btn-sm">Edit Post</button></a>
    <br><br>
    <hr>
    <a href="{% url 'Login:view_comment' pk=post.pk %}" >Comments: </a> {{post.comments.all|length}}
    <a href="{% url 'Login:add_comment' pk=post.pk %}" style="float: right;" ><button  type="button" class="btn btn-primary btn-sm">Add Comment</button></a>
    <br><br>
</div>
{% endfor %}



{% endblock %}

Blog/templates/Login/login.html
{% extends 'Login/base.html' %}

{% block body_block %}

<div class="jumbotron">
    <form class="form-group" method="post" action="{% url 'Login:index' %}">
        {% csrf_token %}
        <label class="form-label" for="username">Username </label>
        <input type="text" id="username" name="username" class="form-control" placeholder="Enter the username">

        <label class="form-label" for="password">Password </label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter the password">
        <br>
        <div align="center">
            <input type="submit" value="Login" class="btn btn-dark">
        </div>
        {% if valid %}
        <div>
            <h3>Invalid Username or password</h3>
        </div>
        {% endif %}
    </form>
</div>


{% endblock %}

Blog/templates/Login/post_detail.html
{% extends 'Login/base.html' %}
{% block body_block %}


<div class="jumbotron">
    <h1>{{post_detail.title}}</h1><hr>
    <h5>Author: {{post_detail.author}}</h5><hr>
    <p>{{post_detail.content}}</p>
    <small>Posted on {{post_detail.creation_date}}</small><br>
    <a href="{% url 'Login:delete' pk=post_detail.pk %}" ><button type="button" class="btn btn-danger btn-sm">Delete Post</button></a> &nbsp;
    <a href="{% url 'Login:update' pk=post_detail.pk %}" ><button type="button" class="btn btn-warning btn-sm">Edit Post</button></a>
    <br><br>
    <hr>
    <div>
        <h5 style="color:green;">Comments:</h5>
        <a href="{% url 'Login:add_comment' pk=post_detail.pk %}" style="float: right;" ><button  type="button" class="btn btn-primary btn-sm">Add Comment</button></a>
    {% for comment in post_detail.comments.all %}
        <span style="color:blue;">{{comment.name}}: </span> {{comment.comment_text}}
        <br>
        <small>commented on : {{comment.commented_date}}</small><br>
        <a href="{% url 'Login:update_comment' pk=comment.pk %}" ><button type="button" class="btn btn-warning btn-sm">Edit</button></a> &nbsp;
        <a href="{% url 'Login:delete_comment' pk=comment.pk %}" ><button type="button" class="btn btn-danger btn-sm">Delete</button></a>
        <br><br>
    {% endfor %}
    </div>
</div>




{% endblock %}

Blog/templates/Login/register.html
{% extends 'Login/base.html' %}

{% block body_block %}

    {% if registered %}
        <h1>Thanks for the Registration</h1>
    {% else %}
        <div class="jumbotron">
            <h1>Enter the details for Registration</h1>
            <form class="form-group" method="post" action="{% url 'Login:register' %}">
                {% csrf_token %}
                {% for field in user_form %}
                  <p>
                    {{ field.label_tag }}
                    {{ field }}
                    {% if field.help_text %}
                      <small style="color: grey">{{ field.help_text }}</small>
                    {% endif %}
                    {% for error in field.errors %}
                      <p style="color: red">{{ error }}</p>
                    {% endfor %}
                  </p>
                {% endfor %}
                <button type="submit" class="btn btn-primary">Sign up</button>
            </form>
        </div>
    {% endif %}

{% endblock %}

Blog/templates/Login/update_comment.html
{% extends 'Login/base.html' %}

{% block body_block %}
<h1>Update Comment {{comment.comment_text}}</h1>
<form method="post">
    {{form.as_p}}
    {% csrf_token %}
    <input class="btn btn-success btn-sm" type="submit" value="Update">
    <a href="{% url 'Login:home' %}"><button type="button" class="btn btn-warning btn-sm">Cancel</button></a>
</form>
{% endblock %}

Blog/templates/Login/update_post.html
{% extends 'Login/base.html' %}

{% block body_block %}
<h1>Update {{post.title}}</h1>
<form method="post">
    {{form.as_p}}
    {% csrf_token %}
    <input class="btn btn-primary" type="submit" value="Update">
    <a href="{% url 'Login:home' %}"><button class="btn btn-primary">Cancel</button></a>
</form>
{% endblock %}